uploads = []
generated = []

[[outputs]]
id = "iloBCXekLbrVgyKDLwJRa"
uri = "file://README.md"
type = "text"
title = "FitBoom — Batafsil README"

[[outputs]]
id = "66_1F57voJsMLhDRs0TTu"
uri = "file://mobile_spec/FITBOOM_REACT_NATIVE.md"
type = "text"
title = "FitBoom React Native — To'liq Loyiha Kodi"
