import { createContext, useContext, useEffect, useState } from "react";

type Language = "uz" | "ru" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    "app.name": "FitBoom",
    "home.welcome": "Sport hayotingizni boshqaring",
    "home.near_gyms": "Sizga eng yaqin zallar",
    "home.view_all": "Barchasini ko'rish",
    "home.sorted_by_distance": "Masofaga qarab saralangan",
    "home.nearby_gyms_desc": "Yaqin atrofdagi sport zallari",
    "home.loading": "Yuklanmoqda...",
    "home.booking_success": "Muvaffaqiyatli bron qilindi!",
    "home.credits_used": "kalit ishlatildi",
    "home.error": "Xatolik",
    "home.no_gyms_on_map": "Haritada ko'rsatish uchun koordinatali zallar yo'q",
    "home.search_results": "Qidiruv natijalari",
    "home.no_results": "Zallar topilmadi",
    "home.no_gyms_yet": "Hozircha zallar mavjud emas",
    "home.unknown_distance": "Masofa noma'lum",
    "home.my_courses": "Mening Kurslarim",
    "home.purchased": "Sotib olingan",
    "home.videos_soon": "Hozircha video kurslar mavjud emas. Tez orada yangi kurslar qo'shiladi!",
    "home.gyms_title": "Sport Zallari",
    "home.no_gyms_filter": "Sizning qidiruv shartingizga mos sport zal topilmadi",
    "home.gym_slots_title": "Bron qilish",
    "home.gym_slots_desc": "O'zingizga qulay vaqtni tanlang",
    "home.no_slots": "Vaqt slotlari yo'q. Vaqtsiz bron qilishingiz mumkin.",
    "home.confirm": "Tasdiqlash",
    "home.scanner_desc": "Tez orada bu funksiya ishga tushadi. QR-kodni skanerlash orqali sport zaliga kirishingiz mumkin bo'ladi.",
    "courses.no_courses_desc": "Hozircha video kurslar mavjud emas. Tez orada yangi kurslar qo'shiladi!",
    "bookings.no_history_desc": "Hozircha tarix yo'q",
    "profile.title": "Profil",
    "profile.edit": "Tahrirlash",
    "profile.edit_title": "Profilni tahrirlash",
    "profile.name": "Ism",
    "profile.enter_name": "Ismingizni kiriting",
    "profile.save": "Saqlash",
    "profile.saving": "Saqlanmoqda...",
    "profile.user": "Foydalanuvchi",
    "profile.no_phone": "Telefon raqam yo'q",
    "profile.male": "👨 Erkak",
    "profile.female": "👩 Ayol",
    "profile.age": "yosh",
    "profile.credits_title": "Kalitlar soni",
    "profile.credits_count": "kalit",
    "profile.expired_message": "Muddat tugadi! Kalit yangilang",
    "profile.expiring_soon": "Diqqat:",
    "profile.days_left": "kun qoldi",
    "profile.renew": "Yangilash",
    "profile.topup": "To'ldirish",
    "profile.history_title": "Bronlar tarixi",
    "profile.no_history": "Hozircha tarix yo'q",
    "profile.unknown_gym": "Noma'lum zal",
    "profile.missed": "Muddati o'tgan",
    "profile.success_update": "Profil yangilandi",

    "settings.title": "Sozlamalar",
    "settings.admin": "Admin sifatida kirish",
    "settings.admin_desc": "Boshqaruv paneliga kirish",
    "settings.gym_owner": "Zal egasi sifatida kirish",
    "settings.gym_owner_desc": "Zalingizni boshqaring",
    "settings.partner": "Hamkor bo'lish",
    "settings.partner_desc": "Zalingizni platformaga qo'shing",
    "settings.admin_login": "Admin kirish",
    "settings.admin_login_desc": "Boshqaruv paneliga kirish uchun parolni kiriting",
    "settings.gym_owner_login": "Zal egasi kirish",
    "settings.gym_owner_login_desc": "Zalingizni boshqarish uchun kirish kodini kiriting",
    "settings.enter_password": "Parolni kiriting",
    "settings.enter_code": "Kirish kodini kiriting (masalan: ABC123)",
    "settings.login": "Kirish",
    "settings.checking": "Tekshirilmoqda...",
    "settings.hall_name": "Zal/Darslik/Dastur nomi",
    "settings.hall_placeholder": "Masalan: FitGym Chilonzor",
    "settings.phone": "Telefon raqami",
    "settings.send": "Yuborish",
    "settings.sending": "Yuborilmoqda...",
    "settings.request_sent": "So'rovingiz yuborildi. Tez orada siz bilan bog'lanamiz!",
    "settings.max_price": "Maksimal narx",
    "settings.price_filter": "Narx bo'yicha filtr...",

    "courses.title": "Video Kurslar",
    "courses.desc": "Professional video darsliklar to'plami",
    "courses.no_courses": "Hozircha video kurslar mavjud emas",
    "courses.purchased": "Sotib olingan",
    "courses.view": "Kursni Ko'rish",
    "courses.buy": "ga sotib olish",
    "courses.free": "Bepul",
    "courses.videos": "ta video",

    "map.title": "Eng Yaqin Zallar",
    "map.desc": "Haritada sport zallarni ko'ring va tanlang",
    "map.locate_me": "Mening Joylashuvim",
    "map.your_location": "Sizning joylashuvingiz",
    "map.view_on_google": "Google Maps'da ko'rish",
    "map.title_short": "Harita",

    "nav.home": "Asosiy",
    "nav.gyms": "Zallar",
    "nav.classes": "Darslar",
    "nav.bookings": "Bronlar",
    "nav.scanner": "Skaner",
    
    "common.back": "Orqaga",
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.error": "Xatolik",
    "common.success": "Muvaffaqiyatli",
    "common.loading": "Yuklanmoqda...",
    "common.search": "Qidirish...",
    "common.all": "Hammasi",

    "payment.buy_keys": "Kalit sotib olish",
    "payment.subscription_active": "Joriy obuna",
    "payment.days_left": "kun qoldi",
    "payment.new_subscription": "Yangi 30 kunlik obuna boshlang",
    "payment.popular": "Mashhur",
    "payment.keys": "kalit",
    "payment.som": "so'm",
    "payment.buy": "Sotib olish",
    "payment.card_info": "Karta ma'lumotlari",
    "payment.card_number": "Karta raqami",
    "payment.card_holder": "Karta egasi",
    "payment.amount_to_pay": "To'lov summasi",
    "payment.transfer_instruction": "Ushbu summani yuqoridagi karta raqamiga o'tkazing va chekni yuboring",
    "payment.send_receipt": "Chekni yuborish",
    "payment.uploading": "Yuklanmoqda...",
    "payment.success": "Muvaffaqiyatli",
    "payment.receipt_sent": "Chek yuborildi. Admin tasdiqlashini kuting.",
    "payment.error": "Xatolik",
    "payment.upload_error": "Chek yuborishda xatolik",
    "payment.copied": "Nusxa olindi",
    "payment.pending_exists": "Sizda kutilayotgan to'lov mavjud",
    "payment.remaining_payment": "Qoldiq to'lov",
    "payment.unpaid_amount": "Yetmayotgan summa",
    "payment.keys_for": "kalit uchun qoldiq",
    "payment.remaining_desc": "To'lovni yakunlang! Qoldiq summani to'lab, chekni yuboring",
    "payment.pay_remaining": "Qoldiqni to'lash"
  },
  ru: {
    "app.name": "FitBoom",
    "home.welcome": "Управляйте своей спортивной жизнью",
    "home.near_gyms": "Ближайшие залы",
    "home.view_all": "Посмотреть все",
    "home.sorted_by_distance": "Отсортировано по расстоянию",
    "home.nearby_gyms_desc": "Тренажерные залы поблизости",
    "home.loading": "Загрузка...",
    "home.booking_success": "Успешно забронировано!",
    "home.credits_used": "ключей использовано",
    "home.error": "Ошибка",
    "home.no_gyms_on_map": "Нет залов с координатами для отображения на карте",
    "home.search_results": "Результаты поиска",
    "home.no_results": "Залы не найдены",
    "home.no_gyms_yet": "Залы пока не добавлены",
    "home.unknown_distance": "Расстояние неизвестно",
    "home.my_courses": "Мои Курсы",
    "home.purchased": "Куплено",
    "home.videos_soon": "Видеокурсы пока недоступны. Скоро появятся новые курсы!",
    "home.gyms_title": "Спортивные Залы",
    "home.no_gyms_filter": "Залы по вашему запросу не найдены",
    "home.gym_slots_title": "Бронирование",
    "home.gym_slots_desc": "Выберите удобное время",
    "home.no_slots": "Нет доступных слотов. Вы можете забронировать без выбора времени.",
    "home.confirm": "Подтвердить",
    "home.scanner_desc": "Скоро эта функция станет доступной. Вы сможете войти в спортзал, отсканировав QR-код.",
    "courses.no_courses_desc": "Видеокурсы пока недоступны. Скоро появятся новые курсы!",
    "bookings.no_history_desc": "Истории пока нет",

    "profile.title": "Профиль",
    "profile.edit": "Редактировать",
    "profile.edit_title": "Редактировать профиль",
    "profile.name": "Имя",
    "profile.enter_name": "Введите ваше имя",
    "profile.save": "Сохранить",
    "profile.saving": "Сохранение...",
    "profile.user": "Пользователь",
    "profile.no_phone": "Нет номера телефона",
    "profile.male": "👨 Мужчина",
    "profile.female": "👩 Женщина",
    "profile.age": "лет",
    "profile.credits_title": "Количество ключей",
    "profile.credits_count": "ключей",
    "profile.expired_message": "Срок истёк! Обновите ключ",
    "profile.expiring_soon": "Внимание:",
    "profile.days_left": "дней осталось",
    "profile.renew": "Обновить",
    "profile.topup": "Пополнить",
    "profile.history_title": "История бронирований",
    "profile.no_history": "Истории пока нет",
    "profile.unknown_gym": "Неизвестный зал",
    "profile.missed": "Просрочено",
    "profile.success_update": "Профиль обновлен",

    "settings.title": "Настройки",
    "settings.admin": "Войти как админ",
    "settings.admin_desc": "Доступ к панели управления",
    "settings.gym_owner": "Войти как владелец зала",
    "settings.gym_owner_desc": "Управляйте вашим залом",
    "settings.partner": "Стать партнером",
    "settings.partner_desc": "Добавьте ваш зал на платформу",
    "settings.admin_login": "Вход для админа",
    "settings.admin_login_desc": "Введите пароль для доступа к панели управления",
    "settings.gym_owner_login": "Вход для владельца зала",
    "settings.gym_owner_login_desc": "Введите код доступа для управления залом",
    "settings.enter_password": "Введите пароль",
    "settings.enter_code": "Введите код доступа (например: ABC123)",
    "settings.login": "Войти",
    "settings.checking": "Проверка...",
    "settings.hall_name": "Название зала/курса/программы",
    "settings.hall_placeholder": "Например: FitGym Чиланзар",
    "settings.phone": "Номер телефона",
    "settings.send": "Отправить",
    "settings.sending": "Отправка...",
    "settings.request_sent": "Ваш запрос отправлен. Мы свяжемся с вами в ближайшее время!",
    "settings.max_price": "Максимальная цена",
    "settings.price_filter": "Фильтр по цене...",

    "courses.title": "Видео Курсы",
    "courses.desc": "Коллекция профессиональных видеоуроков",
    "courses.no_courses": "Видеокурсы пока недоступны",
    "courses.purchased": "Куплено",
    "courses.view": "Смотреть курс",
    "courses.buy": "купить за",
    "courses.free": "Бесплатно",
    "courses.videos": "видео",

    "map.title": "Ближайшие залы",
    "map.desc": "Смотрите и выбирайте залы на карте",
    "map.locate_me": "Мое местоположение",
    "map.your_location": "Ваше местоположение",
    "map.view_on_google": "Посмотреть на Google Maps",
    "map.title_short": "Карта",

    "nav.home": "Главная",
    "nav.gyms": "Залы",
    "nav.classes": "Занятия",
    "nav.bookings": "Брони",
    "nav.scanner": "Сканер",

    "common.back": "Назад",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.error": "Ошибка",
    "common.success": "Успешно",
    "common.loading": "Загрузка...",
    "common.search": "Поиск...",
    "common.all": "Все",

    "payment.buy_keys": "Купить ключи",
    "payment.subscription_active": "Текущая подписка",
    "payment.days_left": "дней осталось",
    "payment.new_subscription": "Начните новую 30-дневную подписку",
    "payment.popular": "Популярный",
    "payment.keys": "ключей",
    "payment.som": "сум",
    "payment.buy": "Купить",
    "payment.card_info": "Данные карты",
    "payment.card_number": "Номер карты",
    "payment.card_holder": "Владелец карты",
    "payment.amount_to_pay": "Сумма оплаты",
    "payment.transfer_instruction": "Переведите эту сумму на указанную карту и отправьте чек",
    "payment.send_receipt": "Отправить чек",
    "payment.uploading": "Загрузка...",
    "payment.success": "Успешно",
    "payment.receipt_sent": "Чек отправлен. Ожидайте подтверждения админа.",
    "payment.error": "Ошибка",
    "payment.upload_error": "Ошибка отправки чека",
    "payment.copied": "Скопировано",
    "payment.pending_exists": "У вас есть ожидающая оплата",
    "payment.remaining_payment": "Остаток оплаты",
    "payment.unpaid_amount": "Недостающая сумма",
    "payment.keys_for": "ключей, остаток",
    "payment.remaining_desc": "Завершите оплату! Оплатите остаток и отправьте чек",
    "payment.pay_remaining": "Оплатить остаток"
  },
  en: {
    "app.name": "FitBoom",
    "home.welcome": "Manage your sports life",
    "home.near_gyms": "Gyms near you",
    "home.view_all": "View all",
    "home.sorted_by_distance": "Sorted by distance",
    "home.nearby_gyms_desc": "Gyms in your vicinity",
    "home.loading": "Loading...",
    "home.booking_success": "Successfully booked!",
    "home.credits_used": "credits used",
    "home.error": "Error",
    "home.no_gyms_on_map": "No gyms with coordinates to display on map",
    "home.search_results": "Search results",
    "home.no_results": "No gyms found",
    "home.no_gyms_yet": "No gyms available yet",
    "home.unknown_distance": "Distance unknown",
    "home.my_courses": "My Courses",
    "home.purchased": "Purchased",
    "home.videos_soon": "No video courses available yet. New courses coming soon!",
    "home.gyms_title": "Gyms",
    "home.no_gyms_filter": "No gyms found matching your search",
    "home.gym_slots_title": "Booking",
    "home.gym_slots_desc": "Choose a convenient time",
    "home.no_slots": "No time slots available. You can book without a specific time.",
    "home.confirm": "Confirm",
    "home.scanner_desc": "This feature will be available soon. You will be able to enter the gym by scanning a QR code.",
    "courses.no_courses_desc": "No video courses available yet. New courses coming soon!",
    "bookings.no_history_desc": "No history yet",

    "profile.title": "Profile",
    "profile.edit": "Edit",
    "profile.edit_title": "Edit Profile",
    "profile.name": "Name",
    "profile.enter_name": "Enter your name",
    "profile.save": "Save",
    "profile.saving": "Saving...",
    "profile.user": "User",
    "profile.no_phone": "No phone number",
    "profile.male": "👨 Male",
    "profile.female": "👩 Female",
    "profile.age": "years old",
    "profile.credits_title": "Credit Balance",
    "profile.credits_count": "credits",
    "profile.expired_message": "Expired! Please renew",
    "profile.expiring_soon": "Warning:",
    "profile.days_left": "days left",
    "profile.renew": "Renew",
    "profile.topup": "Top up",
    "profile.history_title": "Booking History",
    "profile.no_history": "No history yet",
    "profile.unknown_gym": "Unknown Gym",
    "profile.missed": "Expired",
    "profile.success_update": "Profile updated",

    "settings.title": "Settings",
    "settings.admin": "Login as Admin",
    "settings.admin_desc": "Access management panel",
    "settings.gym_owner": "Login as Gym Owner",
    "settings.gym_owner_desc": "Manage your gym",
    "settings.partner": "Become a Partner",
    "settings.partner_desc": "Add your gym to the platform",
    "settings.admin_login": "Admin Login",
    "settings.admin_login_desc": "Enter password to access the management panel",
    "settings.gym_owner_login": "Gym Owner Login",
    "settings.gym_owner_login_desc": "Enter access code to manage your gym",
    "settings.enter_password": "Enter password",
    "settings.enter_code": "Enter access code (e.g., ABC123)",
    "settings.login": "Login",
    "settings.checking": "Checking...",
    "settings.hall_name": "Gym/Course/Program Name",
    "settings.hall_placeholder": "e.g., FitGym Chilonzor",
    "settings.phone": "Phone Number",
    "settings.send": "Send",
    "settings.sending": "Sending...",
    "settings.request_sent": "Your request has been sent. We will contact you soon!",
    "settings.max_price": "Max price",
    "settings.price_filter": "Price filter...",

    "courses.title": "Video Courses",
    "courses.desc": "Professional video tutorial collections",
    "courses.no_courses": "No video courses available yet",
    "courses.purchased": "Purchased",
    "courses.view": "View Course",
    "courses.buy": "buy for",
    "courses.free": "Free",
    "courses.videos": "videos",

    "map.title": "Gyms Near You",
    "map.desc": "See and select gyms on the map",
    "map.locate_me": "My Location",
    "map.your_location": "Your location",
    "map.view_on_google": "View on Google Maps",
    "map.title_short": "Map",

    "nav.home": "Home",
    "nav.gyms": "Gyms",
    "nav.classes": "Classes",
    "nav.bookings": "Bookings",
    "nav.scanner": "Scanner",

    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.error": "Error",
    "common.success": "Success",
    "common.loading": "Loading...",
    "common.search": "Search...",
    "common.all": "All",

    "payment.buy_keys": "Buy Keys",
    "payment.subscription_active": "Active subscription",
    "payment.days_left": "days left",
    "payment.new_subscription": "Start a new 30-day subscription",
    "payment.popular": "Popular",
    "payment.keys": "keys",
    "payment.som": "UZS",
    "payment.buy": "Buy",
    "payment.card_info": "Card Details",
    "payment.card_number": "Card number",
    "payment.card_holder": "Card holder",
    "payment.amount_to_pay": "Amount to pay",
    "payment.transfer_instruction": "Transfer this amount to the card above and send the receipt",
    "payment.send_receipt": "Send Receipt",
    "payment.uploading": "Uploading...",
    "payment.success": "Success",
    "payment.receipt_sent": "Receipt sent. Please wait for admin confirmation.",
    "payment.error": "Error",
    "payment.upload_error": "Error sending receipt",
    "payment.copied": "Copied",
    "payment.pending_exists": "You have a pending payment",
    "payment.remaining_payment": "Remaining Payment",
    "payment.unpaid_amount": "Unpaid amount",
    "payment.keys_for": "keys, remaining",
    "payment.remaining_desc": "Complete payment! Pay the remaining amount and send the receipt",
    "payment.pay_remaining": "Pay Remaining"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(
    (localStorage.getItem("language") as Language) || "uz"
  );

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
